package com.xuek.greendao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.xuek.greendao.dao.User;
import com.xuek.greendao.dao.ImMessage;

import com.xuek.greendao.dao.UserDao;
import com.xuek.greendao.dao.ImMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig imMessageDaoConfig;

    private final UserDao userDao;
    private final ImMessageDao imMessageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        imMessageDaoConfig = daoConfigMap.get(ImMessageDao.class).clone();
        imMessageDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        imMessageDao = new ImMessageDao(imMessageDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(ImMessage.class, imMessageDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        imMessageDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ImMessageDao getImMessageDao() {
        return imMessageDao;
    }

}
